# Generated by Django 5.2 on 2025-04-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom complet du client'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone du client'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='proprietaire_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom du propriétaire'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='proprietaire_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone du propriétaire'),
        ),
    ]
