# Generated by Django 5.2 on 2025-05-06 18:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rendezvous_client_name_rendezvous_client_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
